apiVersion: knative.dev/v1
kind: NooBaaSource
metadata:
  name: bad
spec:
  name: bad noobaa source
  source:
    rpcUrl: ws://noobaa-mgmt.somewhwere:1717/
    rpcSecret: noobaa-mgmt.somewhwere
    bucket: first-bucket
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
